apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pollen-alert.fullname" . }}-config
data:
  pollen-alert.toml: |
    latitude = {{ .Values.config.latitude | quote }}
    longitude = {{ .Values.config.longitude | quote }}
    lookahead_hours = {{ .Values.config.lookaheadHours }}
    fetch_interval_hours = {{ .Values.config.fetchIntervalHours }}
    notify_hours = [{{ .Values.config.notifyHours | join ", " }}]
    {{- range .Values.config.allergens }}

    [[allergens]]
    name = {{ .name | upper | quote }}
    threshold = {{ .threshold }}
    {{- end }}
