apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pollen-alert.fullname" . }}-secrets
type: Opaque
stringData:
  pushoverToken: {{ .Values.secrets.pushoverToken | quote }}
  pushoverUserKey: {{ .Values.secrets.pushoverUserKey | quote }}
