apiVersion: v1
kind: Service
metadata:
  name: {{ include "pollen-alert.fullname" . }}
  labels:
    app: {{ include "pollen-alert.fullname" . }}
spec:
  selector:
    app: {{ include "pollen-alert.fullname" . }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
